# Generated by workspace - do not edit manually
from pathlib import Path

import pytest

ACTUAL_DIR = Path(__file__).parent / "plan_snapshots_actual"
EXPECTED_DIR = Path(__file__).parent / "plan_snapshots"

# (example_id, sanitized_address, nested)
TEST_CASES = [
    ('existing-org', 'module_atlas_org_module_resource_policy[0]_mongodbatlas_resource_policy_block_wildcard_ip[0]', True),
    ('existing-org', 'module_atlas_org_module_resource_policy[0]_mongodbatlas_resource_policy_cluster_tier_limits[0]', True),
    ('existing-org', 'module_atlas_org_module_resource_policy[0]_mongodbatlas_resource_policy_require_maintenance_window[0]', True),
    ('existing-org', 'module_atlas_org_module_resource_policy[0]_mongodbatlas_resource_policy_restrict_vpc_peering_mods[0]', True),
]


@pytest.mark.parametrize("example_id,address,nested", TEST_CASES)
def test_plan_snapshot(
    example_id: str, address: str, nested: bool, file_regression
) -> None:
    subpath = f"{example_id}/{address}" if nested else f"{example_id}_{address}"
    actual_file = ACTUAL_DIR / f"{subpath}.yaml"
    expected_file = EXPECTED_DIR / f"{subpath}.yaml"
    assert actual_file.exists(), f'Actual file not found: {actual_file}'
    file_regression.check(actual_file.read_text(), fullpath=expected_file)
